make = ['BMW', 'FIAT', 'Chrysler', 'Mazda', 'Nissan', 'Alfa Romeo',
       'Toyota', 'Porsche', 'Saab', 'Audi', 'GMC', 'Hyundai', 'Honda',
       'Suzuki', 'Oldsmobile', 'Kia', 'Chevrolet', 'Cadillac', 'Dodge',
       'Lincoln', 'Pontiac', 'Mercedes-Benz', 'Subaru', 'Volkswagen',
       'Ford', 'Volvo', 'Buick', 'Acura', 'Lexus', 'Land Rover',
       'Mitsubishi', 'Lotus', 'Infiniti', 'Scion', 'Genesis', 'Maserati',
       'HUMMER', 'Tesla', 'Plymouth']

car_model = ['Class - 1', 'Class - 2', 'Class - 3']


transmision_type = ['Manual', 'Automatic', 'Automated-Manual', 'Direct-Drive']

driven_wheel = ['2WD-Rear','2WD-Front', '4WD']

vehicle_style = ['Coupe', 'Convertible', 'Sedan', 'Hatchback', 'Wagon', 'SUV',
       'Minivan', 'Pickup']

bensin = ['aqua','2tang','susu']


class_1_series = ['1 Series M', '1 Series', '2 Series', '3 Series Gran Turismo',
       '3 Series', '300', '350Z', '370Z', '4 Series Gran Coupe',
       '4 Series', '4C', '4Runner', '5 Series Gran Turismo', '5 Series',
       '7 Series', '718 Cayman', '9-3 Griffin', '9-3', '9-4X', '9-5',
       '9-7X', 'A3', 'A4 allroad', 'A4', 'A5', 'A6', 'A7',
       'Acadia Limited', 'Acadia', 'ActiveHybrid 5', 'allroad quattro',
       'allroad', 'Armada', 'Aspen', 'ATS Coupe', 'ATS-V', 'ATS',
       'Avalanche', 'Avalon Hybrid', 'Avalon', 'Aviator',
       'B-Class Electric Drive', 'Black Diamond Avalanche', 'Blackwood',
       'Bolt EV', 'Boxster', 'C-Class', 'C70', 'Cadenza', 'Camaro',
       'Cayenne', 'Cayman S', 'Cayman', 'CC', 'Challenger', 'Charger',
       'CLA-Class', 'CLK-Class', 'CLS-Class', 'Continental',
       'Corvette Stingray', 'Corvette', 'Crossfire', 'CT6', 'CTS Coupe',
       'CTS-V Coupe', 'CTS-V Wagon', 'CTS-V', 'CTS Wagon', 'CTS', 'CX-9',
       'DeVille', 'Discovery Sport', 'Discovery', 'DTS', 'Durango',
       'E-Class', 'Edge', 'Eldorado', 'Elise', 'Enclave', 'Envision',
       'Envoy XL', 'Eos', 'Equus', 'ES 300h', 'ES 350', 'Escalade EXT',
       'Escalade Hybrid', 'Escalade', 'Evora', 'Exige', 'EX',
       'Expedition', 'Explorer', 'F-150', 'Flex', 'FX35', 'FX45', 'FX50',
       'FX', 'G Convertible', 'G Coupe', 'G Sedan', 'G37 Convertible',
       'G37 Coupe', 'G37 Sedan', 'G37', 'G80', 'Genesis', 'Ghibli',
       'GL-Class', 'GLA-Class', 'GLC-Class', 'GLE-Class Coupe',
       'GLE-Class', 'GLS-Class', 'Golf R', 'GS 200t', 'GS 300', 'GS 350',
       'GS 430', 'GS 450h', 'GS 460', 'GX 460', 'GX 470', 'H3',
       'Highlander Hybrid', 'Highlander', 'i3', 'Impala', 'IS 250 C',
       'IS 250', 'IS 300', 'IS 350 C', 'IS 350', 'IS F', 'JX', 'K900',
       'LaCrosse', 'Levante', 'LR2', 'LR3', 'LR4', 'LS 430', 'LS 460',
       'LS', 'Lucerne', 'LX 470', 'M-Class', 'M2', 'M35', 'M37', 'M3',
       'M45', 'M4', 'M56', 'Macan', 'Mark LT', 'Maxima', 'M', 'MDX',
       'MKC', 'MKS', 'MKT', 'MKX', 'MKZ', 'Model S',
       'Murano CrossCabriolet', 'Murano', 'Mustang', 'Navigator',
       'NX 300h', 'Odyssey', 'Pacifica', 'Park Avenue', 'Pathfinder',
       'Phaeton', 'Pilot', 'Prowler', 'Q3', 'Q45', 'Q50', 'Q5',
       'Q60 Convertible', 'Q60 Coupe', 'Q70', 'Q7', 'Quest', 'QX56',
       'QX60', 'QX70', 'QX80', 'QX', 'R-Class', 'Ram Pickup 1500',
       'Range Rover Evoque', 'Range Rover Sport', 'RAV4 EV', 'RC 200t',
       'RC 300', 'RC 350', 'RC F', 'RDX', 'Ridgeline', 'RL', 'RLX',
       'Routan', 'RS 4', 'RS 5', 'RX 350', 'RX 400h', 'RX 450h', 'S3',
       'S4', 'S5', 'S60 Cross Country', 'S60', 'S6', 'S80', 'S90',
       'Santa Fe', 'SC 430', 'Sedona', 'Sequoia', 'Seville',
       'Shelby GT350', 'Shelby GT500', 'Sienna', 'Sierra 1500 Hybrid',
       'Sierra 1500', 'Silverado 1500 Hybrid', 'Silverado 1500',
       'SLC-Class', 'SLK-Class', 'Sorento', 'SQ5', 'SRX', 'SS', 'SSR',
       'STS', 'Suburban', 'Tacoma', 'Tahoe Hybrid', 'Tahoe', 'Taurus',
       'Thunderbird', 'Titan', 'TL', 'TLX', 'Touareg 2', 'Touareg',
       'Town and Country', 'Town Car', 'Transit Wagon', 'Traverse',
       'TT RS', 'TT', 'TTS', 'Tundra', 'V60 Cross Country', 'V60', 'X3',
       'X4', 'X5', 'X6', 'XC60', 'XC70', 'XC90', 'XT5', 'XTS',
       'Yukon Hybrid', 'Yukon XL', 'Yukon', 'Z4 M', 'Z4', 'ZDX']


class_2_series = ['1 Series', '124 Spider', '2 Series', '200', '3 Series', '300',
       '300M', '350Z', '370Z', '3', '4Runner', '500e', '500', '500L',
       '500X', '5', '626', '6', '86', '9-2X', '9-3 Griffin', '9-3',
       '9-4X', '9-5', '9-7X', 'A3', 'A4', 'Acadia', 'Accord Crosstour',
       'Accord Hybrid', 'Accord Plug-In Hybrid', 'Accord', 'Alero',
       'allroad quattro', 'Altima Hybrid', 'Altima', 'Amanti', 'Armada',
       'Aspen', 'Astro Cargo', 'Astro', 'ATS Coupe', 'ATS', 'Aurora',
       'Avalanche', 'Avalon Hybrid', 'Avalon', 'Avenger', 'Aviator',
       'Azera', 'Aztek', 'B-Class Electric Drive', 'B-Series Truck',
       'B-Series', 'B9 Tribeca', 'Baja', 'Beetle Convertible', 'Beetle',
       'Black Diamond Avalanche', 'Blazer', 'Bolt EV', 'Bonneville',
       'Borrego', 'Bravada', 'BRZ', 'C-Class', 'C-Max Hybrid', 'C30',
       'C70', 'Cabrio', 'Cadenza', 'Caliber', 'Camaro', 'Camry Hybrid',
       'Camry Solara', 'Camry', 'Canyon', 'Captiva Sport', 'Caravan',
       'Cascada', 'Catera', 'CC', 'Celica', 'Century', 'Challenger',
       'Charger', 'City Express', 'Civic', 'CLA-Class', 'CL', 'Cobalt',
       'Colorado', 'Concorde', 'Continental', 'Corolla', 'CR-V', 'CR-Z',
       'Crossfire', 'Crosstour', 'Crosstrek', 'Crown Victoria',
       'Cruze Limited', 'Cruze', 'CT 200h', 'CTS Coupe', 'CTS Wagon',
       'CX-3', 'CX-5', 'CX-7', 'CX-9', 'Dakota', 'Dart', 'Defender',
       'Diamante', 'Discovery Series II', 'Discovery Sport', 'Discovery',
       'Durango', 'e-Golf', 'E-Series Van', 'E-Series Wagon',
       'Eclipse Spyder', 'Eclipse', 'Edge', 'Elantra Coupe',
       'Elantra Touring', 'Elantra', 'Element', 'Enclave', 'Encore',
       'Endeavor', 'Entourage', 'Envision', 'Envoy XL', 'Envoy XUV',
       'Envoy', 'Eos', 'Equator', 'Equinox', 'ES 300', 'ES 330', 'ES 350',
       'Escape Hybrid', 'Escape', 'EuroVan', 'EX35', 'EX',
       'Explorer Sport Trac', 'Explorer Sport', 'Explorer',
       'Express Cargo', 'Express', 'F-150 Heritage', 'F-150', 'Fiesta',
       'Firebird', 'Fit EV', 'Fit', 'Five Hundred', 'FJ Cruiser', 'Flex',
       'Focus RS', 'Focus ST', 'Focus', 'Forester', 'Forte', 'FR-S',
       'Freelander', 'Freestar', 'Freestyle', 'Frontier', 'Fusion Hybrid',
       'Fusion', 'FX35', 'G Coupe', 'G Sedan', 'G20', 'G35', 'G37 Coupe',
       'G37 Sedan', 'G37', 'G5', 'G6', 'G8', 'Galant', 'Genesis Coupe',
       'Genesis', 'GLA-Class', 'GLC-Class', 'GLI', 'GLK-Class',
       'Golf Alltrack', 'Golf GTI', 'Golf R', 'Golf SportWagen', 'Golf',
       'Grand Am', 'Grand Caravan', 'Grand Prix', 'Grand Vitara',
       'GS 300', 'GTI', 'GTO', 'H3', 'H3T', 'HHR', 'Highlander', 'HR-V',
       'HS 250h', 'i-MiEV', 'I30', 'I35', 'ILX Hybrid', 'ILX',
       'Impala Limited', 'Impala', 'Impreza WRX', 'Impreza', 'Insight',
       'Integra', 'Intrepid', 'Intrigue', 'IS 200t', 'IS 250', 'IS 300',
       'IS 350', 'Jetta GLI', 'Jetta Hybrid', 'Jetta SportWagen', 'Jetta',
       'Jimmy', 'Journey', 'Juke', 'Kizashi', 'LaCrosse',
       'Lancer Evolution', 'Lancer Sportback', 'Lancer', 'Leaf', 'Legacy',
       'LeSabre', 'LHS', 'LR2', 'LS', 'Lucerne', 'Magnum',
       'Malibu Classic', 'Malibu Hybrid', 'Malibu Limited', 'Malibu Maxx',
       'Malibu', 'Mark LT', 'Matrix', 'Maxima', 'Mazdaspeed 3',
       'Mazdaspeed 6', 'Mazdaspeed MX-5 Miata', 'Mazdaspeed Protege',
       'Metris', 'Millenia', 'MKC', 'MKS', 'MKX', 'MKZ Hybrid', 'MKZ',
       'Montana SV6', 'Montana', 'Monte Carlo', 'Montero Sport',
       'Montero', 'MPV', 'MR2 Spyder', 'Murano', 'Mustang', 'MX-5 Miata',
       'Neon', 'New Beetle', 'Nitro', 'NV200', 'NX 200t', 'NX 300h',
       'Odyssey', 'Optima Hybrid', 'Optima', 'Outback', 'Outlander Sport',
       'Outlander', 'Pacifica', 'Park Avenue', 'Passat', 'Passport',
       'Pathfinder', 'Pilot', 'Prelude', 'Prius c', 'Prius Prime',
       'Prius v', 'Prius', 'Prowler', 'PT Cruiser', 'Q3', 'Q40', 'Q50',
       'Q5', 'Q60 Coupe', 'Quest', 'QX4', 'QX50', 'R32', 'Raider',
       'Rainier', 'Ram Cargo', 'Ram Pickup 1500', 'Ram Wagon', 'Ranger',
       'RAV4 Hybrid', 'RAV4', 'RC 200t', 'RDX', 'Regal', 'Rendezvous',
       'Ridgeline', 'Rio', 'Rogue Select', 'Rogue', 'Rondo', 'Routan',
       'RSX', 'RX 300', 'RX 330', 'RX-8', 'S-10', 'S2000', 'S40', 'S60',
       'S80', 'Safari Cargo', 'Safari', 'Santa Fe Sport', 'Santa Fe',
       'Savana Cargo', 'Savana', 'Sebring', 'Sedona', 'Sentra', 'Sienna',
       'Sierra 1500 Classic', 'Sierra 1500 Hybrid', 'Sierra 1500',
       'Sierra 1500HD', 'Sierra C3', 'Silhouette',
       'Silverado 1500 Classic', 'Silverado 1500 Hybrid',
       'Silverado 1500', 'Solstice', 'Sonata Hybrid', 'Sonata', 'Sonic',
       'Sonoma', 'Sorento', 'Soul EV', 'Soul', 'Spark EV', 'Sportage',
       'SRX', 'SSR', 'Stratus', 'Supra', 'SX4', 'Tacoma', 'Taurus X',
       'Taurus', 'tC', 'Terrain', 'Terraza', 'Thunderbird', 'Tiburon',
       'Tiguan', 'Titan', 'TL', 'TLX', 'Torrent', 'Touareg 2',
       'Town and Country', 'Tracker', 'TrailBlazer EXT', 'TrailBlazer',
       'Transit Connect', 'Transit Wagon', 'Traverse', 'Trax', 'Tribeca',
       'Tribute Hybrid', 'Tribute', 'Truck', 'TSX Sport Wagon', 'TSX',
       'Tucson', 'Tundra', 'Uplander', 'V40', 'V50', 'V60', 'V70',
       'Veloster', 'Venture', 'Venza', 'Veracruz', 'Verano', 'Verona',
       'Vibe', 'Voyager', 'Windstar Cargo', 'Windstar', 'WRX', 'X1', 'X3',
       'xB', 'XC60', 'XC70', 'XC90', 'XC', 'XG300', 'XG350', 'XL-7',
       'XL7', 'XT5', 'Xterra', 'XV Crosstrek', 'Z3', 'Zephyr']

class_3_series = ['Mazda 2 Series', 'Mazda 3 Series', '500', '500L', '500X', '5', '626', 'Accent', 'Aerio',
       'Alero', 'Avenger', 'Aveo', 'B-Series Truck', 'B-Series', 'Beetle',
       'Cabrio', 'Caliber', 'Camry Solara', 'Canyon', 'Caravan',
       'Cavalier', 'Celica', 'Civic', 'Classic', 'Cobalt', 'Colorado',
       'Corolla iM', 'Corolla', 'CR-Z', 'Cruze Limited', 'Cruze', 'Cube',
       'CX-3', 'Dart', 'ECHO', 'Eclipse', 'Elantra Coupe', 'Elantra GT',
       'Elantra Touring', 'Elantra', 'Equator', 'Escort', 'Esteem',
       'F-150 Heritage', 'Fiesta', 'Firebird', 'Fit', 'Focus', 'Forenza',
       'Forte', 'Freestar', 'Frontier', 'G3', 'G5', 'G6', 'Golf',
       'Grand Am', 'Grand Vitara', 'HHR', 'HR-V', 'iA', 'Impreza', 'iM',
       'Insight', 'Integra', 'iQ', 'Jetta', 'Jimmy', 'Kizashi',
       'Lancer Sportback', 'Lancer', 'Lumina', 'Malibu Classic',
       'Malibu Maxx', 'Matrix', 'Mazdaspeed Protege', 'Metro',
       'Mirage G4', 'Mirage', 'Neon', 'New Beetle', 'Outlander Sport',
       'Prius c', 'Prizm', 'Protege5', 'Protege', 'PT Cruiser', 'Rabbit',
       'Raider', 'Ram Cargo', 'Ranger', 'Reno', 'Rio', 'Rondo', 'S-10',
       'Sebring', 'Sentra', 'Sephia', 'Sierra 1500 Classic',
       'Silverado 1500 Classic', 'Sonic', 'Sonoma', 'Soul', 'Spark',
       'Spectra', 'Stratus', 'Sunfire', 'Supra', 'Swift', 'SX4', 'tC',
       'Tiburon', 'Tracker', 'Tribute', 'Truck', 'Uplander', 'Veloster',
       'Verona', 'Versa Note', 'Versa', 'Vibe', 'Vitara', 'Voyager', 'xA',
       'xB', 'xD', 'Yaris iA', 'Yaris']


